export const IMAGES = {
    number1 : new URL('/1.png', import.meta.url).href,
    number2 : new URL('/2.png', import.meta.url).href,
    number3 : new URL('/3.png', import.meta.url).href,
    whoWeAreMain : new URL('/whoweare1.png', import.meta.url).href,
    tShirt : new URL('/tShirt.png', import.meta.url).href,
    logoBlack : new URL('/logoBlack.png', import.meta.url).href,
    home1: new URL('/home1.png', import.meta.url).href,
    footer1: new URL('/footer1.png', import.meta.url).href,
    facebook: new URL('/Facebook.svg', import.meta.url).href,
    gmail: new URL('/Gmail.svg', import.meta.url).href,
    tiktok: new URL('/Tiktok.svg', import.meta.url).href,
    instagram: new URL('/Instagram.svg', import.meta.url).href,
    whatsApp: new URL('/WhatsApp.svg', import.meta.url).href,
    tShirtFront: new URL('/t-shirtFront.png', import.meta.url).href,
    tShirtBack: new URL('/t-shirtBack.png', import.meta.url).href,
    letterSize: new URL('/letterSize.png', import.meta.url).href,
    tabloid: new URL('/tabloid.png', import.meta.url).href,
}
